import type { AdminAnalyticsData } from '@/lib/admin/get-admin-analytics';
import Link from 'next/link';
import { FiBarChart2, FiBookmark, FiEye, FiFileText, FiHeart, FiMessageCircle, FiTrendingUp, FiUsers } from 'react-icons/fi';

const number = new Intl.NumberFormat('ja-JP');

const AdminAnalytics = ({ data }: { data: AdminAnalyticsData }) => {
  const maxDaily = Math.max(1, ...data.dailyPublications.map((day) => day.count));
  const publishRate = data.totalPostCount ? Math.round((data.publishedPostCount / data.totalPostCount) * 100) : 0;
  const categoryTotal = Math.max(1, data.techPostCount + data.businessPostCount);
  const techRate = Math.round((data.techPostCount / categoryTotal) * 100);
  const metrics = [
    { label: '公開記事', value: data.publishedPostCount, note: `公開率 ${publishRate}%`, icon: FiFileText, color: 'bg-[#E8F0F7] text-[#446783]' },
    { label: '総閲覧数', value: data.totalViewCount, note: '公開・下書きを含む累計', icon: FiEye, color: 'bg-[#F2EDE7] text-[#87603F]' },
    { label: 'いいね', value: data.likeCount, note: '記事へのリアクション', icon: FiHeart, color: 'bg-[#F7E8EA] text-[#A14E5D]' },
    { label: 'コメント', value: data.commentCount, note: 'ナレッジへの対話', icon: FiMessageCircle, color: 'bg-[#E9F1EA] text-[#527158]' },
    { label: 'ブックマーク', value: data.bookmarkCount, note: 'あとで読む保存数', icon: FiBookmark, color: 'bg-[#FBF0DE] text-[#96682F]' },
    { label: '投稿メンバー', value: data.contributorCount, note: '公開実績のある人数', icon: FiUsers, color: 'bg-[#EEEAF7] text-[#66508D]' },
  ];

  return <div className="space-y-6">
    <section aria-label="主要指標" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(({ label, value, note, icon: Icon, color }) => <article key={label} className="rounded-2xl border border-[#E7DED5] bg-white p-5 shadow-[0_10px_28px_rgba(73,52,38,0.045)]"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#7C756F]">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight text-[#3F4854]">{number.format(value)}</p></div><span className={`flex size-11 items-center justify-center rounded-2xl ${color}`}><Icon /></span></div><p className="mt-3 text-xs text-[#968B82]">{note}</p></article>)}</section>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(280px,0.8fr)]">
      <section className="rounded-3xl border border-[#E7DED5] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="flex items-center gap-2 text-sm font-bold text-[#3F4854]"><FiBarChart2 className="text-[#A66334]" />直近30日の公開推移</p><p className="mt-1 text-xs text-[#817970]">初回公開日を基準に集計</p></div><span className="rounded-full bg-[#FFF1E4] px-3 py-1 text-xs font-bold text-[#9A5D2E]">計 {data.dailyPublications.reduce((sum, day) => sum + day.count, 0)}件</span></div><div className="mt-6 flex h-52 items-end gap-1" role="img" aria-label="直近30日の日別公開記事数">{data.dailyPublications.map((day, index) => <div key={day.key} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><div title={`${day.label}: ${day.count}件`} className="relative min-h-1 rounded-t-md bg-[linear-gradient(180deg,#C47A45,#8F552F)] transition hover:brightness-110" style={{ height: `${Math.max(3, (day.count / maxDaily) * 100)}%` }}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#3F4854] px-2 py-1 text-[10px] text-white group-hover:block">{day.count}件</span></div>{(index === 0 || index === 14 || index === 29) && <span className="mt-2 whitespace-nowrap text-[9px] text-[#9A9087]">{day.label}</span>}</div>)}</div></section>
      <section className="rounded-3xl border border-[#E7DED5] bg-white p-5 sm:p-6"><p className="font-bold text-[#3F4854]">記事の内訳</p><div className="mt-5 space-y-5"><div><div className="flex justify-between text-xs"><span className="font-semibold text-[#687482]">公開ステータス</span><span className="text-[#8A8179]">全 {data.totalPostCount}件</span></div><div className="mt-2 flex h-3 overflow-hidden rounded-full bg-[#EEEAE6]"><span className="bg-[#59806A]" style={{ width: `${publishRate}%` }} /><span className="bg-[#D7A75D]" style={{ width: `${data.totalPostCount ? (data.draftPostCount / data.totalPostCount) * 100 : 0}%` }} /><span className="bg-[#A66B67]" style={{ flex: data.archivedPostCount }} /></div><div className="mt-2 flex flex-wrap gap-3 text-[11px] text-[#817970]"><span>公開 {data.publishedPostCount}</span><span>下書き {data.draftPostCount}</span><span>アーカイブ {data.archivedPostCount}</span></div></div><div><div className="flex justify-between text-xs"><span className="font-semibold text-[#687482]">公開記事カテゴリ</span><span className="text-[#8A8179]">技術 {techRate}%</span></div><div className="mt-2 flex h-3 overflow-hidden rounded-full"><span className="bg-[#486E95]" style={{ width: `${techRate}%` }} /><span className="flex-1 bg-[#B87747]" /></div><div className="mt-2 flex gap-3 text-[11px] text-[#817970]"><span>技術 {data.techPostCount}</span><span>業務 {data.businessPostCount}</span></div></div></div></section>
    </div>

    <div className="grid gap-6 xl:grid-cols-2"><section className="overflow-hidden rounded-3xl border border-[#E7DED5] bg-white"><header className="flex items-center gap-2 border-b border-[#EEE7E0] px-5 py-4 font-bold text-[#3F4854]"><FiTrendingUp className="text-[#A66334]" />よく読まれている記事</header>{data.topPosts.length ? <ol className="divide-y divide-[#F0EAE4]">{data.topPosts.map((post, index) => <li key={post.id}><Link href={`/post/${post.id}`} className="flex items-center gap-3 px-5 py-4 transition hover:bg-[#FFFCF8]"><span className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-[#F3EAE1] text-xs font-bold text-[#8D512D]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#3F4854]">{post.title}</p><p className="mt-1 text-xs text-[#817970]">{post.author.name}</p></div><div className="text-right text-xs text-[#817970]"><p>{post.viewCount} views</p><p className="mt-1">♥ {post._count.likes}・💬 {post._count.comments}</p></div></Link></li>)}</ol> : <p className="p-10 text-center text-sm text-[#817970]">公開記事はまだありません。</p>}</section><section className="overflow-hidden rounded-3xl border border-[#E7DED5] bg-white"><header className="flex items-center gap-2 border-b border-[#EEE7E0] px-5 py-4 font-bold text-[#3F4854]"><FiUsers className="text-[#526E8B]" />投稿メンバー</header>{data.topContributors.length ? <ol className="divide-y divide-[#F0EAE4]">{data.topContributors.map((user, index) => <li key={user.id} className="flex items-center gap-3 px-5 py-4"><span className="flex size-8 items-center justify-center rounded-full bg-[#E8F0F7] text-xs font-bold text-[#446783]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#3F4854]">{user.name}</p><p className="mt-1 text-xs text-[#817970]">{user.department?.name ?? '部署未設定'}</p></div><span className="text-sm font-bold text-[#526E8B]">{user._count.posts}記事</span></li>)}</ol> : <p className="p-10 text-center text-sm text-[#817970]">投稿メンバーはまだいません。</p>}</section></div>
  </div>;
};

export default AdminAnalytics;
