ALTER TYPE "AdminAuditAction" ADD VALUE 'USER_ROLE_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'USER_STATUS_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'USER_SESSION_REVOKED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'DEPARTMENT_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'DEPARTMENT_RENAMED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'DEPARTMENT_DELETED';
